# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.20
# 
# >> macros
%define     crda_lib /usr/lib/crda
# << macros

Name:       wireless-regdb
Summary:    802.11 wireless networking regulatory database
Version:    2009.11.25
Release:    1
Group:      System/Networking
License:    ISC
BuildArch:  noarch
URL:        http://wireless.kernel.org/en/developers/Regulatory/
Source0:    http://wireless.kernel.org/download/wireless-regdb/wireless-regdb-%{version}.tar.bz2
Source100:  wireless-regdb.yaml


%description
This package contains the wireless regulatory database used by all
cfg80211 based Linux wireless drivers.




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# don't actually rebuild
exit
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
%doc LICENSE
%doc README
%{crda_lib}/*
%{_mandir}/man5/regulatory.bin.5.gz
# >> files
# << files


