# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       wireless-regdb

# >> macros
# << macros

Summary:    802.11 wireless networking regulatory database
Version:    2013.01.11
Release:    1
Group:      System/Networking
License:    ISC
BuildArch:  noarch
URL:        http://wireless.kernel.org/en/developers/Regulatory/
Source0:    http://www.kernel.org/pub/software/network/wireless-regdb/wireless-regdb-2013.01.11.tar.xz
Source100:  wireless-regdb.yaml
BuildRequires:  openssl
BuildRequires:  python
BuildRequires:  python-M2Crypto

%description
This package contains the wireless regulatory database used by all
cfg80211 based Linux wireless drivers.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%doc LICENSE
%doc README
%{_libdir}/crda/pubkeys/*.pem
%{_libdir}/crda/regulatory.bin
%doc %{_mandir}/man5/regulatory.bin.5.gz
# >> files
# << files
